---
title: "AuDHDer?"
draft: true
editor: visual
---

# A loose collection of reflections on my autism/adhd diagnosis

Recently, I confirmed some the ND labels I've collected and self-diagnosed through formal psychological assessment. I'm still processing my diagnosis and what it means to me, but I want to share some stories of how and why I sought out these labels, the challenges I encountered, and the upsides of it all.

## Good stuff

Let's start with the good stuff. 

1. So many new tools for understanding myself

Lots of people who get diagnosed later in life talk about how everything suddenly make sense. I can't say *everything* makes sense, but exploring and claiming my identity as an neurodivergent person has given me new and important tools for understanding myself and my relationships. Needing to detail and track all my neurodiverse traits was both a barrier to and immensely rewarding part of seeking a diagnosis. I happen to like writing lists, and have a pretty established journalling practice from when I was younger, so it wasn't too hard to find examples of my neurodiverse traits and formulate a coherent explanation of why I wanted a diagnosis. Even if I wasn't able to access a formal assessment, or if I didn't get a diagnosis, I found immense comfort and utility in the exercise of sitting down and sifting through my childhood "weirdness", the ways in which my academic giftedness masked my other struggles, and all the cool things my brain does easily but others find difficult. When you've only had the language of the neurotypical experience to describe yourself, it's easy to fall into narratives of deficiency and self-criticism. 

2. Higher-dimensional Language for sharing myself with others

Stories are part of being human, and so much of the push for diversity in media is about seeing people like you, experiences like yours, to feel less alone, but also to learn from. One of my favourite things about friendship is living vicariously through others, through their stories, through the moments shared joy and excitement and even grief and disappointment. I wonder if my love of story has anything to do with wanting to find the words to describe my own experiences, to lessen the feeling of otherness that often seems to accompany neurodiversity.

Intensity and frequencies were the missing story dimensions that my diagnosis journey gave me. Most people can relate to snapshots of neurodivergent experiences -- feeling overstimulated by a busy festive season, forgetting why you entered a room, or making a social faux pas. Maybe this is why people express scepticism or surprise about my diagnosis -- "Isn't everyone a little autistic?", "I never would have guessed", or "Those are **totally** normal experiences". 

Speaking of normal, in preparation for my assessment, I had to wring details of my childhood out of my parents' foggy memories. What I got was mostly variations on "you were normal", "you did x at a normal time", "just Google what a normal child does". I was their first child. What did they know about normal? What even is "normal"?

## Challenges

4. Internalised and cultural stigma

My mother has tried multiple times to discourage me from seeking psychological services, often with anxious insistences that "there's nothing wrong with you". I've had to gently but firmly remind her my life is my own and whatever consequences there might be to my decisions, my mistakes are my own to make. Those little episodes might seem trite if you have functional boundaries with your family, or even like totally outrageous meddling, but carving out space to go to therapy and seek a diagnosis was an achievement in so many ways for me. 

I have the privilege of shaping my life in ways that work for me and my brain. That wasn't a privilege my parents had. In a lot of ways, they didn't have the luxury of exploring their neurodiverse needs. They did what they needed to do to survive, to carve out a successful life, with the tools they had available to them. Knowledge about how my brain works is valuable to me. It's worth the many thousands of dollars I've spent on therapy appointments and assessments. But only because it helps me narrow down where I should move towards in the seemingly infinite space of potential and opportunities afforded to me as a // middle-class, highly educated, English speaking professional // in a first world country. Shrink that space to the limited options that my parents had, and paying strangers to give you medical labels that could lead to discrimination seems at the very least indulgent, if not totally self-sabotaging.

5. Financial cost

There's a lot that can be, and has been said about inequality in accessing mental health care. In an ideal world, mental health care services would be freely and easily accessible for people regardless of socio-economic class. There's not much I can add to that aspiration. But I can say something about overcoming certain cognitive barrier to paying for mental health care that remain *even if* by most measures you can *afford* mental health care services. To be more specific, I'm talking about being a position to spend a few thousand dollars on a vacation, or updating your wardrobe, or even more than that to upgrade your car, and yet still *feeling* like mental health care is not affordable or valuable enough to justify giving something else up. 

My patchy employment history is a story for another day, and really looks a lot like other autistic stories of underemployment, but for at least a year or two before I started regular therapy, I had enough resources to pay for therapy. It definitely didn't feel like I did

3. Noticing masking and self-denial

I often think of neurodivergent people as variations on Obleck. Obleck is a newtonian fluid that is gloopy and viscous when moved slowly, but becomes rigid and brittle when sufficient force is applied. For neurodiverse people that force can come in "unusual" forms such as sensory overload --- shutting down in noisy or busy spaces, an inability to switch their attention away from screens, 

How do you respond under stress? What kinds of stress impact you?

Ice cube, melt under pressure. 

4. My shopping cart of dsm labels

Depression, anxiety, trauma, HSP, giftedness, over-excitability, sensory sensitivities, dosas.
<thoughts on paper showing brains of OCD, ADHD, Austism> are indistinguishable

"What if we don't diagnose you?". What are you looking to get out of this process?
- Framework for understanding myself and how my brain works better 
- Directions to tools, books, ideas suitable for me, not just the everyman targeted by "how to hack your life" listicles.
- A finer sieve for sifting through self-care and self-help ideas.

However, I know that isn't necessarily the case for other neurodiverse people, and the gathering and organising that is required to seek a diagnosis can be a significant barrier. 


why did I seek it?

- this article: ABC -- late diagnosis
- giftedness assessment
- internet sleuthing
- depression, career limbo

how much did it cost, and how did I decide if it was worth it?

- time
- money
- uncertainty -- would I even be diagnosed? what if this is all just distraction from "getting my life together"?
- reparenting -- would i seek this service out for my child?

barriers and challenges to getting a diagnosis

- wait times
- getting a referral -- keeping a list of traits, observations etc.
- cost // valuing my mental health
- childhood history from parents
- ableism, stigma -- internal and from parents, community

disclosing my suspicions and my diagnosis

- helpful responses -- simon, felix, susanna
- self-knowledge and a permeable filter -- 
- not so great experiences -- university disability services
- well-meaning but able-ist -- karol/amali, laura p

was it worth it in the end?

- not at the end, still processing and learning
- value in vocabulary and frameworks
- material impact on a relationship between two neurodiverse people
- opening for asking for help with "easy things"
