project:
  type: website
  render:
    - "*.qmd"
    - "!posts/drafts/**/*.qmd"
  resources: 
    - "_redirects"

execute:
  freeze: true

website:
  title: "Cynthia Huang"
  site-url: https://www.cynthiahqy.com
  open-graph: true
  twitter-card: 
    creator: "@cynthiahqy"
  
  repo-url: https://github.com/cynthiahqy/digital-garden
  repo-actions: [edit, issue]

  navbar:
    right:
      - blog.qmd
      - gallery.qmd
      - CV.qmd
      - icon: github
        href: https://github.com/cynthiahqy
      - icon: twitter
        href: https://twitter.com/cynthiahqy

  page-footer:
    right: "This website is built with ❤️  and [Quarto](https://quarto.org/), by Cynthia Huang. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

format:
  html:
    theme: simplex
    css: styles.css
    from: markdown+emoji



