project:
  type: website
  render:
    - "*.qmd"
    - "!posts/drafts/"

website:
  title: "Cynthia Huang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cynthiahqy
      - icon: twitter
        href: https://twitter.com/cynthiahqy
format:
  html:
    theme: simplex
    toc: true
    css: styles.css



