project:
  type: website
  render:
    - "*.qmd"
    - "!posts/drafts/**/*.qmd"
  resources:
    - "_redirects"

execute:
  freeze: true

website:
  title: "Cynthia Huang"
  site-url: https://www.cynthiahqy.com
  description: "Cynthia Huang's Website"
  open-graph: true
  twitter-card:
    creator: "@cynthiahqy"

  repo-url: https://github.com/cynthiahqy/digital-garden
  repo-actions: [edit, issue]

  navbar:
    right:
      - now.qmd
      - blog.qmd
      - sidebar:gallery
      - research.qmd
      - text: Talks
        href: https://talks.cynthiahqy.com
      - CV.qmd
      - icon: github
        href: https://github.com/cynthiahqy
      - icon: linkedin
        href: https://www.linkedin.com/in/cynthiahqy/
      # - icon: twitter
      #   href: https://twitter.com/cynthiahqy
      # - icon: envelope-at-fill
      #   href: mailto:cynthia.huang@monash.edu
      - icon: rss
        href: blog.xml

  sidebar:
    - id: gallery
      title: "Gallery"
      contents:
        - gallery.qmd
        - gallery/sketchbook/index.qmd
        - gallery/podcasts.qmd

  page-footer:
    right: "This website is built with ❤️  and [Quarto](https://quarto.org/), by Cynthia Huang. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

format:
  html:
    theme: simplex
    css: styles.css
    from: markdown+emoji
