---
title: "Gallery"
listing:
  - id: sketchnotes
    contents: 
      - "gallery/sketchnotes/"
    type: grid
    image-height: 350px
    grid-columns: 2
    fields: [image, title, based-on]
    field-display-names:
      based-on: "from:"
    categories: true
    grid-item-align: center
    sort: date asc
  - id: templates
    contents:
      - "gallery/templates/"
    type: default 
    image-align: left
    image-height: 200px
    image-placeholder: "templates/placeholder.png"
    fields: [image, title]
    sort: date-modified desc
page-layout: full
#title-block-banner: true
---

## Podcast Episodes

Episodes of [The Random Sample](https://www.therandomsample.com.au/) hosted by yours truly:

-   [EP 81: Open-sourcing Data Science Education with Professor Mine Çetinkaya-Rundel](https://www.therandomsample.com.au/podcast/open-education/)
-   [EP 79: Law & Stats: What's a Statistician Doing in Court? with Ian Gordon](https://www.therandomsample.com.au/podcast/statisticians-in-legal-cases/)
-   [EP 75: Probing Large Language Models & ChatGPT with Simon Angus](https://www.therandomsample.com.au/podcast/chatgpt/)
-   [EP 72: Future Proofing as Data Changes the World with Dana Ma](https://www.therandomsample.com.au/podcast/future-proofing/)
-   [EP 70: The Statistical Society of Australia's 60th Birthday with Ian Gordon and Jessica Kasza](https://www.therandomsample.com.au/podcast/ssa-60th/)

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/73TelUFx5Vrfdx8ilNEBXE?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

## Interviews and Profiles

About me, published by:

-   Australian Research Data Commons (May 2023): [Shaping Research Software: An Interview With Cynthia Huang](https://ardc.edu.au/article/shaping-research-software-an-interview-with-cynthia-huang/)
-   Monash Data Future Institute (Mar 2022): [Monash Data Futures Institute PhD Students](https://www.monash.edu/data-futures-institute/about-us/people/monash-data-futures-institute-phd-students)

## Sketchnotes

**Visual Thinking / Conceptual Illustration / Information Design** by yours truly.

Sketchnotes for lectures, talks, podcast episodes, youtube videos, books, and more.

::: callout
## Attribution

{{< include gallery/_snippet-attribution.md >}}
:::

::: {#sketchnotes}
:::

## Design Notes and Templates

Notes to self on sketching, Inkscape, Quarto, SVG, CSS/HTML, web accessibility.[^1]

[^1]: Disclaimer: the primary audience for these notes is myself, and I make no guarantees about accuracy or quality of the content inside.

::: {#templates}
:::
