# Now

This is a [now page](https://nownownow.com/about), where I occasionally update where I am, what I'm doing, and/or what I'm *trying* to focus on.

## Dec 2025

**📍 Melbourne, Australia**

It's official! As of Aug 20, 2025, I hold a doctoral degree in Mathematics and Statistics from Monash University. My thesis _Unified Principles And Tools For Complex Datasets And Data-Driven Workflows_ was passed with minor revisions and is available online via [Monash University's Library](https://bridges.monash.edu/articles/thesis/Unified_Principles_and_Tools_for_Complex_Datasets_and_Data-Driven_Workflows/29763449?file=56790638).

Since my last update, I've:

- 👩🏻‍🏫 Delivered a guest lecture, ["LLMs for Preparing Data in R"](https://github.com/cynthiahqy/lecture_llms-preparing-data-ellmer), in the _Wild Caught Data_ unit at Monash University
- 🧰 Attended the LMU-NYU-Workshop "Making Data Work: Tools for Better Statistical Practice” in Munich
<!-- - 🕸️ Presented PRITES at internal SoDa workshop -->
- 👩🏻‍🏫 Delivered my ["Quarto for Economists"](https://github.com/cynthiahqy/monash-quarto-aea) workshop for the third time!
- 🐻 co-chairing [WOMBAT2025](https://wombat2025.numbat.space/) (Sep 29-30) -- a two day conference bringing together data folks from industry, academia and government for tutorials and talks on this year's theme of "Designing Data-Driven Discoveries".
- 🇦🇹 Attended VIS2025 (Nov 1-7) in Vienna -- *'Out of the Loop: Enhancing Documentation and Transparency in Collaborative Causal Loop Diagrams to Capture Multiple Perspectives'*

Research wise, I've been thinking a lot about opportunities for dialogue between information visualisation and statistical graphics, while continuing to work on adapting LLMs for data cleaning.

Finally, I'm excited to be joining the [Social Data Science and AI Lab](https://www.stat.lmu.de/soda/en/) at LMU Munich as a post-doctoral researcher from Jan, 2026!

<!-- WOMBAT2025; IEEEVIS 2025 -->

## Apr 2025

**📍 Melbourne, Australia**

I'm finally (almost) PhD-done! I submitted my thesis for examination after a long but rewarding 3 years and 8 months. Although, I wish I had a bit more time to digest it all, I'm grateful to be leaving Melbourne shortly for a very exciting research trip to:

- 🇹🇼 Present recent work on an *integrative framework for investigating and assessing web-scraped datasets for research applications* at National Tsinghua University (Apr 14-18).
- 🇯🇵 Present *'TableCanoniser: Interactive Grammar-Powered Transformation of Messy, Non-Relational Tables to Canonical Tables'* at CHI25 (Apr 27-May 1).

When I get back I'll be continuing to work as a Research Fellow under the wonderful supervision of Rob J Hyndman on tools for ex-post harmonisation, and leveraging LLMs for data preparation.

## Aug 2024

**📍 Vancouver, Canada**, (updated Sep 2024)

~~I'm finished with conference travel for now and settling into Vancouver until late Oct~~. I added another conference to my trip (SmallDataSF -- which was amazing!), and extended my stay in Vancouver through to the end of Nov. Still working on synthesising various definitions of _provenance_ and _provenance-related tools_ across computer science, applied statistics and data science.

I have some gripes with my past-self for over-packing my travel schedule, but really can't complain about my first-time experiences at JSM, posit::conf(2024) and tidy-dev-day! I connected with so many amazing people in the data science and stats community, successfully delivered two new talks and even got to squeeze in a spot of outdoor climbing while in Seattle thanks to an old friend.

## Jun 2024

**📍 Munich, Germany**

After jumping through what felt like endless hoops of approval processes, funding changes and decision fatigue, I've finally started my many months long research trip across Europe & North America. Some upcoming highlights include:

- 🇩🇪 Visiting SODA group at LMU (Jun 13-26)
- 🇦🇹 Presenting on *ex-post harmonisation and the `{xmap}` package* at UseR!, Salzburg (Jul 8-11)
- 🇺🇸 Presenting on *assessing statisical programming skills* at JSM, Portland (Aug 3-9)
- 🇺🇸 Presenting on *Quarto for Knowledge Management* in the *Level up your Data Science Skills* session at posit::conf(2024), Seattle (Aug 12-14)
- 🇨🇦 Visiting the InfoVis group at UBC, Vancouver, (Jul-Nov)

It's hard to express how grateful I am for this opportunity and the support I've gotten, especially from my supervisors, to not only expand my research network, but also to experience so many new cities and countries 🥰.

On great experiences, I may have found one of my favourite Vietnamese restaurants (ever, and that's saying a lot coming from Melbourne) after getting caught in the rain in Amsterdam last week and striking up a conversation with the stranger I was sharing my table with at Saint Jean Deli. The sticky rice Xôi bowl at [bonjour càphê](https://bonjourcaphe.com) is just the perfect blend of textural variety and flavour balance was just *chef's kiss*. I had the fish & dill bowl, and the sticky rice felt amazingly light with just the right amount of bite, while the pickled mango gave the dish a sweet and acidic brightness that just perfectly tied together the slightly saltiness of the fish the aroma of the herbs and chilli. My only regret is that I only found this place on Monday when I was leaving the next morning, and their tasting menu is not available on Monday nights 🥲. I'm seriously considering when/how I might get myself back to Amsterdam to try it.
