---
title: "Podcasts"
---

## The Random Sample Podcast Episodes {#podcast-episodes}

Episodes of [The Random Sample](https://www.therandomsample.com.au/) hosted by yours truly:

-   [EP 100: The Challenges of Publishing Interdisciplinary Research with Prof Xiao-Li Meng](https://www.therandomsample.com.au/podcast/the-publication-puzzle-part-2/)
-   [EP 96: Scientific Graphic Design for Communicating Research with Dr Jess Hopf](https://www.therandomsample.com.au/podcast/scientific-graphic-design/)
-   [EP 94: Understanding Math Struggles with Dr. Jacob Paul](https://www.therandomsample.com.au/podcast/understanding-maths-struggles/)
-   [EP 87: What you need to know about Referendum Polling with Professor Simon Jackman](https://www.therandomsample.com.au/podcast/referendum-polling/)
-   [EP 86: Communicating Statistics & Probability with Professor Jeffrey Rosenthal](https://www.therandomsample.com.au/podcast/jeffrey-rosenthal/)
-   [EP 81: Open-sourcing Data Science Education with Professor Mine Çetinkaya-Rundel](https://www.therandomsample.com.au/podcast/open-education/)
-   [EP 79: Law & Stats: What's a Statistician Doing in Court? with Ian Gordon](https://www.therandomsample.com.au/podcast/statisticians-in-legal-cases/)
-   [EP 75: Probing Large Language Models & ChatGPT with Simon Angus](https://www.therandomsample.com.au/podcast/chatgpt/)
-   [EP 72: Future Proofing as Data Changes the World with Dana Ma](https://www.therandomsample.com.au/podcast/future-proofing/)
-   [EP 70: The Statistical Society of Australia's 60th Birthday with Ian Gordon and Jessica Kasza](https://www.therandomsample.com.au/podcast/ssa-60th/)

and an episode where Professor Peter Taylor interviews me (and others) about being a regular host for the Random Sample:

-   [EP 91: Why host a podcast?](https://www.therandomsample.com.au/podcast/why-host-a-podcast/)

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/73TelUFx5Vrfdx8ilNEBXE?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
